
<?php
// PHP Configuration for SARAH-CORE
// Located at /config.php

function getSystemConfig() {
    $protocol = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') ? "https" : "http";
    $host = $_SERVER['HTTP_HOST'] ?? 'localhost:3002';
    $dynamic_url = "{$protocol}://{$host}";

    // Check for the Cloudflare Uplink File generated by run.sh in the project root
    $uplinkFile = __DIR__ . '/cf_ui.txt';
    if (file_exists($uplinkFile)) {
        $uplinkContent = trim(file_get_contents($uplinkFile));
        if (!empty($uplinkContent)) {
            $dynamic_url = $uplinkContent;
        }
    }

    return [
        'general' => [
            'sender_name' => 'JENNIFER EDWARDS',
            'app_name' => 'PROJECT SARAH',
            'app_url' => rtrim($dynamic_url, '/'),
            'timezone' => 'America/Edmonton',
            'gemini_api_key' => getenv('API_KEY') ?: 'AIzaSyDXAD-SoyiDl4PI4a6-fTL91GdUqT-zRY4',
        ],
        'smtp' => [
            'host' => 'smtp.office365.com',
            'port' => 587,
            'username' => getenv('SMTP_USERNAME_PRIMARY') ?: 'accounting@abfarms.ca',
            'password' => getenv('SMTP_PASSWORD_PRIMARY') ?: 'Covid-1919!!',
            'from_email' => 'accounting@abfarms.ca',
            'encryption' => 'tls',
        ],
        'paths' => [
            'template_root' => __DIR__, 
            'email_template' => 'Deposit.html',
        ]
    ];
}
